In [1]:
#dictionary keyfile
def encryptMarksdata(datafile,keyfile):
    k=dictionarykeyfile(keyfile)
    with open(datafile,'r')as f:
        filedata=f.read().split('\n')
    with open('Datafiles/marklist')as f:
        for mark in filedata:
            line=''
            for n in mark:
                line+=key[n]
            f.write(line+'/n')
    return 
encryptMarksdata()

In [13]:
def keyfile(keypath):
    keypath='Datafiles/key.txt'
    with open(keypath,'w')as f:
        for i in range(0,10):
            if i<6:
                f.write(str(i)+ ' '+str(i+4)+'\n')
            else:
                f.write(str(i)+' '+str(i-6)+'\n')
    return
keyfile(keypath)

    

In [ ]:
def decryptMarksData(encryptedfile,keyfile):
    key=dictionarykeyfile(keyfile)
    n

In [8]:
def factorial(n):
    if n == 0 or n == 1:
        return 1
    return n * factorial(n-1)
factorial(3)

6

In [18]:
keypath='Datafiles/key.txt'
key=keyfile(keypath)
evenkeys={item for item in key}
print(evenkeys)

TypeError: 'NoneType' object is not iterable

## Numpy Library
 Processing N-Dimensional arrays

In [81]:
import numpy as np
li=[1,2,3,'z']
a=np.array(li)
a
b=np.arange(15)
r=np.random.randint(0,100,size=10)
bl=np.random.randint(0,2,size=(3,3))

print(bl)

[[0 1 0]
 [0 0 1]
 [0 1 1]]


In [82]:
bl.ndim
bl.size
bl.shape
bl.dtype
bl.itemsize
bl.nbytes
x=[1,2,3,4,5,6,7,8]
bl[::-1,::-1] 

array([[1, 1, 0],
       [1, 0, 0],
       [0, 1, 0]])

## Pandas
Use cases
  * Data cleaning
  * Data Transformation
  * Data Analysis
### Notations
  * Series
  * Dataframes

In [9]:
import pandas as pd
internal1={'s1':21,'s2':18,'s3':24}
internal1=pd.Series(internal1)
internal2={'s1':20,'s2':19,'s3':24}
internal2=pd.Series(internal2)


s1    20
s2    19
s3    24
dtype: int64

In [18]:
final={'Internal1':internal1,'Internal2':internal2}
final=pd.DataFrame(final)
final.values     #rows of the table
final.columns   #headings or name of all columns

Index(['Internal1', 'Internal2'], dtype='object')

In [21]:
final

Internal1  Internal2
s1         21         20
s2         18         19
s3         24         24

In [26]:
final.values[1,0]

18

In [28]:
for row in final.values:
    print('Internal1-',row[0],'Internal2-',row[1])

Internal1- 21 Internal2- 20
Internal1- 18 Internal2- 19
Internal1- 24 Internal2- 24


In [38]:
final.loc['s4']=[15,18]
final=final.drop(3)

In [41]:
final.values[2,0]=25
final.values[2]=[12,23]
final

Internal1  Internal2
s1         21         20
s2         18         19
s3         12         23
s4         15         18

In [44]:
#Reading CSV file data
import pandas as pd
filepath='Datafiles/Income.csv'
incomedf=pd.read_csv(filepath)
incomedf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [47]:
#Extract income of all states in 2013
# California :57528
for row in incomedf.values:
    print(row[1],':',row[-1])

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [56]:
# Average income of a particular state
summ=0
for i in range(2,11):
    summ=summ+incomedf.values[2][i]
print(summ/len(incomedf.values[2][2:]))

47214.77777777778


In [55]:
summ=0
for row in incomedf.values:
    summ+=row[-2]
print(summ/len(incomedf.values))

50038.8
